# Extra Credit 6
- DAT 301 2024 Spring
- Kelly Sizer


### 1. Implement the following vector subtraction in numpy: u-v

import numpy as np
u = np.array([1, 0])
v = np.array([0, 1])

In [2]:
import numpy as np
u = np.array([1,0])
v = np.array([0,1])



### 2. Multiply the numpy array z with -2:

z = np.array ([2, 4])

In [3]:
z = np.array([2,4])
z = z * -2
print(z)

[-4 -8]


### 3. Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1]. Cast both lists to a numpy array then multiply them together:

a = np.array([1, 2, 3, 4, 5]) b = np.array([1, 0, 1, 0, 1])


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
r = a * b
print(r)
        

[1 0 3 0 5]


### 4. Convert the list [1, 2, 3] and [8, 9, 10] to numpy arrays arr1 and arr2. Then perform Addition , Subtraction , Multiplication , Division and Dot Operation on the arr1 and arr2.

arr1 = np.array([1, 2, 3]) arr2 = np.array([8, 9, 10])

In [5]:
a = [1,2,3]
b = [8,9,10]
arr1 = np.array(a)
arr2 = np.array(b)

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
dot_product = np.dot(arr1, arr2)
print(addition)
print(subtraction)
print(multiplication)
print(division)
print(dot_product)

[ 9 11 13]
[-7 -7 -7]
[ 8 18 30]
[0.125      0.22222222 0.3       ]
56


### 5. Convert the list [1, 2, 3, 4, 5] and [6, 7, 8, 9, 10] to numpy arrays arr1 and arr2. Then find the even and odd numbers from arr1 and arr2.

In [6]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])

print('Arr1:')
print('even -')
print([x for x in arr1 if x % 2 == 0])
print('odd -')
print([x for x in arr1 if (x - 1) % 2 == 0])

print('Arr2:')
print('even -')
print([x for x in arr2 if x % 2 == 0])
print('odd -')
print([x for x in arr2 if (x - 1) % 2 == 0])

Arr1:
even -
[2, 4]
odd -
[1, 3, 5]
Arr2:
even -
[2, 4, 6]
odd -
[3, 5]


### 6. Consider the following list a, convert it to Numpy Array, A.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [7]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

a = np.array(a)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 7. Calculate the numpy array size.

In [8]:


print(np.size(a))

12


### 8. Access the element on the first row and first and second columns.



In [9]:
print(a[0, 0:2])

[1 2]


### 9. Perform matrix multiplication with the numpy arrays A and B.
A = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] B = np.array ([[0, 1], [1, 0], [1, 1], [-1, 0]])


In [10]:
A = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

A = np.array(A)

print(A)
print(B)

C = np.matmul(A, B)
print('Multiplication Result')
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 0  1]
 [ 1  0]
 [ 1  1]
 [-1  0]]
Multiplication Result
[[ 1  4]
 [ 5 12]
 [ 9 20]]
